### ISSUE TITLE
0.40 not working

### ISSUE THREAD

**Issue by Finlito** [TehPuertoRicanSpartan/SRB2MovieTool#1]
i was trying to convert some videos, but even with ffmpeg, ffplay and ffprobe in the same folder it doesnt work

**Comment by TehPuertoRicanSpartan** [comment]
all i'm going to ask is did you read the readme?

**Comment by Finlito** [comment]
yeah

**Comment by Finlito** [comment]
i found out its with certain mp4s, i tried another and it worked
